### ISSUE TITLE
Unable to install, please try again later, ios 18.2 beta 4

### ISSUE THREAD

**Issue by Belligerently** [khcrysalis/Feather#197] opened 2024-11-23 17:26 UTC
When using feather with an official apple dev cert I get an error when trying to install apps "Unable to install "App Name"" under that is says "please try again later" I'm on ios 18.2 beta 4 and I am not sure what to do to fix my issue.

**Comment by khcrysalis** [comment] 2024-11-23 20:30
duplicate of https://github.com/khcrysalis/Feather/issues/182, read the thread for more information

**Closed by khcrysalis** 2024-11-23 20:30 UTC
Labels: duplicate

**Comment by Belligerently** [comment] 2024-11-24 17:28
Thank you
