### ISSUE TITLE
Unable to install any app

### ISSUE THREAD

**Issue by damima-dev** [khcrysalis/Feather#232] opened 2024-12-27 23:12 UTC
### Version

iOS 18.2

### Start going into detail..

When I try to install an app, it says this error.
I've been having this problem since a few days. Help would be appreciated.
![IMG_3312](https://github.com/user-attachments/assets/d74b963f-8f90-4431-9684-86fc79bced18)
_Note: I'm Italian so the text is in Italian, if you don't understand what it says, use [Google Lens](https://lens.google.com)_

**Comment by GottaLoveAng** [comment] 2024-12-27 23:55
ongoing issue happening with everyone at the moment. it will take an indefinite amount of time to fix. use online installation mode for now.

**Comment by khcrysalis** [comment] 2024-12-28 06:52
Duplicate of https://github.com/khcrysalis/Feather/issues/182

**Closed** 2024-12-28 06:52 UTC
Labels: duplicate
