### ISSUE TITLE
Can’t install apps

### ISSUE THREAD

**Issue by neoarz** [khcrysalis/Feather#203] opened 2024-11-27 22:13 UTC
I sign the app but the popup to install the actual app isn’t there
![IMG_3056](https://github.com/user-attachments/assets/750cae11-8915-45b6-b23b-2068f60a2946)
I’m on iOS 18.0 using dev cert latest version of the app

**Comment by GottaLoveAng** [comment] 2024-11-27 23:21
use online install method in settings or whitelist *.localhost.direct in nextdns if you use that

**Comment by neoarz** [comment] 2024-11-27 23:24
> use online install method in settings or whitelist *.localhost.direct in nextdns if you use that

I tried using online install method but it would get the error "unable to install app integrity could not be verified", I know my cert is good since I just got it and installing apps through esign works totally fine. only feather giving me issues.

**Comment by GottaLoveAng** [comment] 2024-11-27 23:27
some apps dont sign properly and im assuming your app works w esign because of the "fix white icon" feature. but online installation should work for a majority of apps.

**Comment by neoarz** [comment] 2024-11-27 23:59
im not using the fix icon feature with esign and also, feather failed all the apps I wanted to install it couldn't even download the newer version of itself lol.

**Comment by neoarz** [comment] 2024-11-27 23:59
> some apps dont sign properly and im assuming your app works w esign because of the "fix white icon" feature. but online installation should work for a majority of apps.

im not using the fix icon feature with esign and also, feather failed all the apps I wanted to install it couldn't even download the newer version of itself lol.

**Comment by GottaLoveAng** [comment] 2024-11-28 00:03
then it may be because you're using an outdated version. no app can update itself as its not possible without some hacky implementation.

**Comment by neoarz** [comment] 2024-11-28 00:57
> then it may be because you're using an outdated version. no app can update itself as its not possible without some hacky implementation.

I tried the latest version, the first version and some and between all giving the same issue. Ive tried multiple ipas too

**Comment by khcrysalis** [comment] 2024-12-13 06:39
duplicate of https://github.com/khcrysalis/Feather/issues/182

**Closed by khcrysalis** 2024-12-13 06:39 UTC
Labels: duplicate
