### ISSUE TITLE
SSL certification

### ISSUE THREAD

**Issue by Manavgupta12** [khcrysalis/Feather#223] opened 2024-12-13 05:47 UTC
### Version

iOS 18.2

### Start going into detail..

When I try to install an app it says unable to install. Please fix the ssl certification and this problem.

**Comment by khcrysalis** [comment] 2024-12-13 06:38
duplicate of https://github.com/khcrysalis/Feather/issues/182

**Closed by khcrysalis** 2024-12-13 06:38 UTC
Labels: bug, duplicate
