### ISSUE TITLE
When installing an app with my private certificate it's not loading the online sign

### ISSUE THREAD

**Issue by NoozPrime** [khcrysalis/Feather#194] opened 2024-11-21 23:04 UTC
Everytime i sign and install the page for online download is not loading i have wifi should work is there a solution?

**Comment by khcrysalis** [comment] 2024-11-22 19:59
Duplicate of https://github.com/khcrysalis/Feather/issues/182, but tldr waiting for a new ssl cert bundle.

**Closed** 2024-11-22 19:59 UTC
Labels: duplicate
