### ISSUE TITLE
I can't install the app

### ISSUE THREAD

**Issue by darknesskill** [khcrysalis/Feather#198] opened 2024-11-24 09:12 UTC
If you press the button to feather import the ipa file, sign ed registration, and install it, and it says to do it again later after a while, and it can't proceed...

**Comment by XEJK** [comment] 2024-11-24 16:07
This is a duplicate of [#182](https://github.com/khcrysalis/Feather/issues/182)

This can be temporarily be solved by enabling the online install method under server options.

**Closed** 2024-11-24 18:52 UTC
Labels: duplicate
