### ISSUE TITLE
Feature request: add date updated / added

### ISSUE THREAD

**Issue by KeyboardChampion** [khcrysalis/Feather#209] opened 2024-12-01 00:49 UTC
It would be nice to see how up to date an app in a repo is

**Comment by dylans509** [comment] 2024-12-04 02:33
Yeah that's a good idea

**Comment by castdrian** [comment] 2024-12-05 20:59
duplicate of https://github.com/khcrysalis/Feather/issues/172

**Closed** 2024-12-05 21:20 UTC
Labels: duplicate
