### ISSUE TITLE
Feather still broken in iOS 18 RC, and now broken in 17.7.

### ISSUE THREAD

**Issue by kitsah** [khcrysalis/Feather#60] opened 2024-09-09 20:02 UTC
Any news on a fix?

**Comment by kitsah** [comment] 2024-09-10 06:52
> it's not feather bug.. local installation is broken since iOS 18~b5.. idk if apple kill it
It's now broken in 17.7 RC too, i think this confirms they killed it.

**Comment by Artichy** [comment] 2024-09-10 12:32
> > > it's not feather bug.. local installation is broken since iOS 18~b5.. idk if apple kill it
> > 
> > 
> > It's now broken in 17.7 RC too, i think this confirms they killed it.
> 
> local install on Feather or any other sign apps should work, but you must install them using Sideloadly or SideStore (using free Apple ID)

I can confirm that installing the app through Xcode works totally fine, signing and installing works as expected.

**Comment by MuzahidGithub** [comment] 2024-09-10 15:11
### Here is a solution if the developer want to implement it 👉 Need to create a local VPN then proxy/redirect traffic of any public internet IP to the local server. iOS no longer accepts install requests from local IPs in 10.* & 127.0.* & 192.168.* range. doesn't matter if you have a SSL. the domain must point to public IP. @khcrysalis  even your localhost.direct domain won't work. this is also same for configuration profiles. can't download them from localhost anymore. for example see the Esign UDID obtaining system. it doesn't work anymore.

**Comment by lxly9** [comment] 2024-09-13 08:19
I am on the newest 18.1 beta but esign device udid profile downloading still works, only feather doesnt seem to.

**Comment by MuzahidGithub** [comment] 2024-09-13 09:30
> I am on the newest 18.1 beta but esign device udid profile downloading still works, only feather doesnt seem to.

which Beta

**Comment by lxly9** [comment] 2024-09-13 11:40
DB3 22B5034e

**Comment by lxly9** [comment] 2024-09-13 16:46
signed it via sidestore and am using my personal dev certificate

**Comment by lxly9** [comment] 2024-09-13 16:54
yeah okay, you wont believe it but its working for me again, same beta, feather sideloaded via sidestore and my own dev cert

**Comment by boierito** [comment] 2024-09-13 17:14
> lxly9

you need a PC to make that, thats not the idea...

**Comment by lxly9** [comment] 2024-09-13 17:35
no no no, feathers sideloading works again, it isnt stuck on ready to install anymore. local installation works again

**Comment by boierito** [comment] 2024-09-13 17:43
> no no no, feathers sideloading works again, it isnt stuck on ready to install anymore. local installation works again

But you need a PC to install sidestore...

**Comment by Xiseous** [comment] 2024-09-16 20:00
> > no no no, feathers sideloading works again, it isnt stuck on ready to install anymore. local installation works again
> 
> But you need a PC to install sidestore...

SideStore installation is a one time thing, then you authenticate on device via loopback VPN, once you install Feather you can just use the DNS blocks and continue like normal

**Comment by yodaluca23** [comment] 2024-09-17 11:30
> iOS no longer accepts install requests from local IPs in 10.* & 127.0.* & 192.168.* range. doesn't matter if you have a SSL. the domain must point to public IP. @khcrysalis  even your localhost.direct domain won't work.

Could we use some sort of proxy then? Proxy the install request to a public proxy, and back to the device?

**Comment by Xiseous** [comment] 2024-09-17 22:24
I'm on 18.1 22B5034e (Dev Beta idk which version),

I've signed Feather via SideStore, completed the developer account mobileprovision/p12 cert using the preassigned AppID and I am sideloading apps without an issue.

Again, followed the guide, downloading apps from repos, signing via Feather, installing via Feather and they work fine on 18.1 Dev Beta

**Comment by Write** [comment] 2024-09-18 03:53
Signing trough ESign, then clicking on "Wi-Fi" in ESign Settings tab, to browse via Safari ESign's files, can still install app locally just fine.

**Comment by AushevAhmad** [comment] 2024-09-18 04:19
> Signing trough ESign, then clicking on "Wi-Fi" in ESign Settings tab, to browse ESign's files, via Safari, can still install app locally just fine.
The only problem is..that it's Feather, not ESign... What's the point of telling a tutorial for ESign if this app is an alternative to ESign?

**Comment by Write** [comment] 2024-09-18 04:40
> > Signing trough ESign, then clicking on "Wi-Fi" in ESign Settings tab, to browse ESign's files, via Safari, can still install app locally just fine.
> 
> The only problem is..that it's Feather, not ESign... What's the point of telling a tutorial for ESign if this app is an alternative to ESign?

Well, showing that there's a method that may be available as a workaround.

**Comment by singurty** [comment] 2024-09-18 15:15
> Signing trough ESign, then clicking on "Wi-Fi" in ESign Settings tab, to browse ESign's files, via Safari, can still install app locally just fine.
This seems to be the only way that works right now that doesn't involve a computer.

**Comment by khcrysalis** [comment] 2024-09-19 00:24
Hey everyone! I've implemented an alternative install method with this commit here https://github.com/khcrysalis/Feather/commit/8f9c4a96203a5cd443de137322c73e8384c3b197

Will be available in the next feather release

**Comment by yodaluca23** [comment] 2024-09-19 00:27
> Hey everyone! I've implemented an alternative install method with this commit here [8f9c4a9](https://github.com/khcrysalis/Feather/commit/8f9c4a96203a5cd443de137322c73e8384c3b197)
> 
> This should be able to install on iOS 18* fine, from the person I've had test at least.
> 
> Will be available in the next feather release.

Is this just a signing server? Or more like a proxy install server? What all is being sent off device?

**Comment by khcrysalis** [comment] 2024-09-19 00:35
> Is this just a signing server? Or more like a proxy install server? What all is being sent off device?

No signing server, rather its just a server which feeds you a plist that feather tries to use to install the application
the application itself is stored on device, not uploaded anywhere: https://github.com/khcrysalis/Feather/blob/main/Shared/Server/Server.swift#L86

**Comment by khcrysalis** [comment] 2024-09-19 00:36
You can get an example of the request by doing.. https://api.palera.in/genPlist?bundleid=a&name=a&version=1&fetchurl=https://example.com

**Comment by yodaluca23** [comment] 2024-09-19 00:37
> > Is this just a signing server? Or more like a proxy install server? What all is being sent off device?
> 
> No signing server, rather its just a server which feeds you a plist that feather tries to use to install the application the application itself is stored on device, not uploaded anywhere: [`main`/Shared/Server/Server.swift#L86](https://github.com/khcrysalis/Feather/blob/main/Shared/Server/Server.swift?rgh-link-date=2024-09-19T00%3A35%3A35Z#L86)

Cool, so it is more like just proxying the installation request... Like I theorized!

**Comment by khcrysalis** [comment] 2024-09-19 02:01
> Remove webviewer when opening api.palera.in?

Honestly, I have no idea how to do this yet but if you have a clue please let me know

> Auto close "Done" window

Sure, I always thought it was weird to keep it open like that

**Comment by khcrysalis** [comment] 2024-09-19 04:50
Fixed in https://github.com/khcrysalis/Feather/releases/tag/v1.0.2, create a new issue regarding installation issues

**Closed by khcrysalis** 2024-09-19 04:50 UTC
