### ISSUE TITLE
Can't install YouTube (ytlite+)

### ISSUE THREAD

**Issue by Ilovecatz17** [khcrysalis/Feather#204] opened 2024-11-28 18:13 UTC
![image](https://github.com/user-attachments/assets/52735e78-3e0f-49d3-abc0-be957a702aa0)

I sign it, which works, I install, online install method, and it does the pop up, I click open in iTunes, and press install, then the little pop up at the bottom shows up, doesn't let me install

**Comment by Konngitas** [comment] 2024-11-29 23:26
I am having a similar problem. I get an install prompt, but cannot install.
![IMG_4054](https://github.com/user-attachments/assets/7c27212d-1be4-4379-bd53-819024fb393f)
iOS 18.1

`[00:26:09] 📝 Version: 18.1
[00:26:09] 📝 Name: iPhone
[00:26:09] 📝 Model: iPhone
[00:26:09] 📝 Feather Version: App Version: 1.1.3

[00:26:19] 📝 app.localhost.direct
[00:26:19] 📝 Server started: Port 4414 for app.localhost.direct
[00:26:37] 📝 Server is shutting down!
[00:26:37] 📝 Server is shutting down!
`

**Comment by castdrian** [comment] 2024-12-02 01:55
You're not using a MapleSign/KravaSign certificate by chance are you, I can reproduce an install failure for any YouTube ipa with any signing application using one of theirs, I don't think this is feather related

**Comment by khcrysalis** [comment] 2024-12-02 02:21
> You're not using a MapleSign/KravaSign certificate by chance are you, I can reproduce an install failure for any YouTube ipa with any signing application using one of theirs, I don't think this is feather related

Both Feather and KravaSign internally use Zsign as their signer, so they'll have *some* of the same issues

**Comment by castdrian** [comment] 2024-12-02 04:54
> Both Feather and KravaSign internally use Zsign as their signer, so they'll have *some* of the same issues

Whilst that is true, this is 100% a KravaSign issue, I can with absolute consistency sign and install any YouTube ipa perfectly fine using my own ADP certificate, trying a Krava one results in the error OP posted and also fails with every other signing app native and online

**Comment by GottaLoveAng** [comment] 2024-12-02 05:37
i've installed multiple youtube ipas using my kravasign certificate though? worked through both feather and esign.

**Comment by castdrian** [comment] 2024-12-02 07:43
> i've installed multiple youtube ipas using my kravasign certificate though? worked through both feather and esign.

Might be their maplesign ones that broke then, I can reproduce this error with maplesign26 consistently at least

**Comment by khcrysalis** [comment] 2024-12-03 01:38
(same thing)

**Comment by castdrian** [comment] 2024-12-03 16:14
Tried with 26 again and it was fine so unclear what happened there, maybe ask them if they know what happened there

**Comment by GottaLoveAng** [comment] 2024-12-03 17:27
yeah i don't believe it could be a certificate issue judging by the error. io usually involves something to do with the device/software/application i believe.

**Comment by castdrian** [comment] 2024-12-03 17:36
yeah I have no clue, didn't get a log of it since I was in a workshop at the time, NIO is some networking lib apple maintains but absolutely unclear why when this happened it happened with just that specific one,  on any and all signing services which is very very odd and does still leave me to believe it had to have been a hiccup tied to it in some way or another, there's just no way that all signing apps even the ones that don't use zsign just fail, anyhow ms26 works now so I'm guessing OPs probably works again as well

**Comment by castdrian** [comment] 2024-12-05 21:08
I was able to reproduce this on any signing service at the time so I feel like this issue can probably be closed as it doesn't seem feather specific

**Closed as not planned** 2024-12-09 10:22 UTC
